In [1]:
import numpy as np
import pandas as pd

In [2]:
X = pd.read_csv("data/data_2d.csvx", header=None)
X

            0          1           2
0   17.930201  94.520592  320.259530
1   97.144697  69.593282  404.634472
2   81.775901   5.737648  181.485108
3   55.854342  70.325902  321.773638
4   49.366550  75.114040  322.465486
5    3.192702  29.256299   94.618811
6   49.200784  86.144439  356.348093
7   21.882804  46.841505  181.653769
8   79.509863  87.397356  423.557743
9   88.153887  65.205642  369.229245
10  60.743854  99.957634  427.605804
11  67.415582  50.368310  292.471822
12  48.318116  99.128953  395.529811
13  28.829972  87.184949  319.031348
14  43.853743  64.473639  287.428144
15  25.313694  83.545294  292.768909
16  10.807727  45.695569  159.663308
17  98.365746  82.697394  438.798964
18  29.146910  66.365107  250.986309
19  65.100302  33.353883  231.711508
20  24.644113  39.540053  163.398161
21  37.559805   1.345728   83.480155
22  88.164506  95.153663  466.265806
23  13.834621  25.494048  100.886430
24  64.410844  77.259838  365.641048
25  68.925992  97.453601  426.140015
26  39.488442  50.856128  235.532389
27  52.463178  59.776510  283.291640
28  48.484787  66.970354  298.581440
29   8.062088  98.242600  309.234109
..        ...        ...         ...
70  30.187692   7.146539   89.539008
71  11.788418  51.697761  181.550683
72  18.292424  61.977976  224.773383
73  96.712668   9.029102  219.567094
74  31.012739  78.283382  298.490216
75  11.397261  61.728693  199.944045
76  17.392556   4.241141   43.915692
77  72.182694  34.539072  256.068378
78  73.980021   3.716493  159.372581
79  94.493058  88.417197  447.132704
80  84.562821  20.241162  233.078830
81  51.742474  11.009748  131.070180
82  53.748590  60.025102  298.814333
83  85.050835  95.736997  451.803523
84  46.777250  90.202206  368.366436
85  49.758434  52.834494  254.706774
86  24.119257  42.102811  168.308433
87  27.201576  29.978749  146.342260
88   7.009596  55.876058  176.810149
89  97.646950   8.147625  219.160280
90   1.382983  84.944087  252.905653
91  22.323530  27.515075  127.570479
92  45.045406  93.520402  375.822340
93  40.163991   0.161699   80.389019
94  53.182740   8.170316  142.718183
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

[100 rows x 3 columns]

In [3]:
type(X)

pandas.core.frame.DataFrame

In [4]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB

In [5]:
X.head()

           0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486