In [2]:
import pandas as pd
from pandas_datareader import data

In [4]:
companies = ["MSFT", "GOOG", "YHOO", "AMZN"]
p = data.DataReader(companies, data_source="yahoo", start="2010-01-01", end="2016-12-31")
type(p)

pandas.core.frame.DataFrame

In [9]:
p.head()

Attributes        High                                     Low              \
Symbols           AMZN        GOOG       MSFT YHOO        AMZN        GOOG
Date
2009-12-31  137.279999  310.679321  30.990000  NaN  134.520004  307.986847
2010-01-04  136.610001  312.721039  31.100000  NaN  133.139999  310.103088
2010-01-05  135.479996  311.891449  31.100000  NaN  131.809998  308.761810
2010-01-06  134.729996  310.907837  31.080000  NaN  131.649994  301.220856
2010-01-07  132.320007  303.029083  30.700001  NaN  128.800003  294.410156

Attributes                        Open              ...      Close       \
Symbols          MSFT YHOO        AMZN        GOOG  ...       MSFT YHOO
Date                                                ...
2009-12-31  30.480000  NaN  137.089996  310.356445  ...  30.480000  NaN
2010-01-04  30.590000  NaN  136.250000  311.449310  ...  30.950001  NaN
2010-01-05  30.639999  NaN  133.429993  311.563568  ...  30.959999  NaN
2010-01-06  30.520000  NaN  134.600006  310.907837  ...  30.770000  NaN
2010-01-07  30.190001  NaN  132.009995  302.731018  ...  30.450001  NaN

Attributes      Volume                                Adj Close              \
Symbols           AMZN        GOOG        MSFT YHOO        AMZN        GOOG
Date
2009-12-31   4523000.0   2455400.0  31929700.0  NaN  134.520004  307.986847
2010-01-04   7599900.0   3937800.0  38409100.0  NaN  133.899994  311.349976
2010-01-05   8851900.0   6048500.0  49749600.0  NaN  134.690002  309.978882
2010-01-06   7178800.0   8009000.0  58182400.0  NaN  132.250000  302.164703
2010-01-07  11030200.0  12912000.0  50559700.0  NaN  130.000000  295.130463

Attributes
Symbols          MSFT YHOO
Date
2009-12-31  24.241983  NaN
2010-01-04  24.615801  NaN
2010-01-05  24.623755  NaN
2010-01-06  24.472631  NaN
2010-01-07  24.218124  NaN

[5 rows x 24 columns]

In [7]:
p["Open"].head()

Symbols           AMZN        GOOG       MSFT  YHOO
Date
2009-12-31  137.089996  310.356445  30.980000   NaN
2010-01-04  136.250000  311.449310  30.620001   NaN
2010-01-05  133.429993  311.563568  30.850000   NaN
2010-01-06  134.600006  310.907837  30.879999   NaN
2010-01-07  132.009995  302.731018  30.629999   NaN

In [8]:
p["Volume"].head()

Symbols           AMZN        GOOG        MSFT  YHOO
Date
2009-12-31   4523000.0   2455400.0  31929700.0   NaN
2010-01-04   7599900.0   3937800.0  38409100.0   NaN
2010-01-05   8851900.0   6048500.0  49749600.0   NaN
2010-01-06   7178800.0   8009000.0  58182400.0   NaN
2010-01-07  11030200.0  12912000.0  50559700.0   NaN

### Extracting with .loc and iloc

In [12]:
p.transpose()

Date                  2009-12-31    2010-01-04    2010-01-05    2010-01-06  \
Attributes Symbols
High       AMZN     1.372800e+02  1.366100e+02  1.354800e+02  1.347300e+02
           GOOG     3.106793e+02  3.127210e+02  3.118914e+02  3.109078e+02
           MSFT     3.099000e+01  3.110000e+01  3.110000e+01  3.108000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AMZN     1.345200e+02  1.331400e+02  1.318100e+02  1.316500e+02
           GOOG     3.079868e+02  3.101031e+02  3.087618e+02  3.012209e+02
           MSFT     3.048000e+01  3.059000e+01  3.064000e+01  3.052000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AMZN     1.370900e+02  1.362500e+02  1.334300e+02  1.346000e+02
           GOOG     3.103564e+02  3.114493e+02  3.115636e+02  3.109078e+02
           MSFT     3.098000e+01  3.062000e+01  3.085000e+01  3.088000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AMZN     1.345200e+02  1.339000e+02  1.346900e+02  1.322500e+02
           GOOG     3.079868e+02  3.113500e+02  3.099789e+02  3.021647e+02
           MSFT     3.048000e+01  3.095000e+01  3.096000e+01  3.077000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AMZN     4.523000e+06  7.599900e+06  8.851900e+06  7.178800e+06
           GOOG     2.455400e+06  3.937800e+06  6.048500e+06  8.009000e+06
           MSFT     3.192970e+07  3.840910e+07  4.974960e+07  5.818240e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AMZN     1.345200e+02  1.339000e+02  1.346900e+02  1.322500e+02
           GOOG     3.079868e+02  3.113500e+02  3.099789e+02  3.021647e+02
           MSFT     2.424198e+01  2.461580e+01  2.462375e+01  2.447263e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2010-01-07    2010-01-08    2010-01-11    2010-01-12  \
Attributes Symbols
High       AMZN     1.323200e+02  1.336800e+02  1.328000e+02  1.298200e+02
           GOOG     3.030291e+02  2.996759e+02  3.002770e+02  2.971473e+02
           MSFT     3.070000e+01  3.088000e+01  3.076000e+01  3.040000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AMZN     1.288000e+02  1.290300e+02  1.292100e+02  1.265500e+02
           GOOG     2.944102e+02  2.926516e+02  2.951006e+02  2.921002e+02
           MSFT     3.019000e+01  3.024000e+01  3.012000e+01  2.991000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AMZN     1.320100e+02  1.305600e+02  1.326200e+02  1.289900e+02
           GOOG     3.027310e+02  2.940872e+02  3.002770e+02  2.968940e+02
           MSFT     3.063000e+01  3.028000e+01  3.071000e+01  3.015000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AMZN     1.300000e+02  1.335200e+02  1.303100e+02  1.273500e+02
           GOOG     2.951305e+02  2.990649e+02  2.986128e+02  2.933322e+02
           MSFT     3.045000e+01  3.066000e+01  3.027000e+01  3.007000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AMZN     1.103020e+07  9.830500e+06  8.779400e+06  9.096300e+06
           GOOG     1.291200e+07  9.509900e+06  1.451960e+07  9.769600e+06
           MSFT     5.055970e+07  5.119740e+07  6.875470e+07  6.591210e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AMZN     1.300000e+02  1.335200e+02  1.303100e+02  1.273500e+02
           GOOG     2.951305e+02  2.990649e+02  2.986128e+02  2.933322e+02
           MSFT     2.421812e+01  2.438515e+01  2.407497e+01  2.391590e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2010-01-13    2010-01-14  ...    2016-12-16  \
Attributes Symbols                              ...
High       AMZN     1.297100e+02  1.303800e+02  ...  7.651300e+02
           GOOG     2.922889e+02  2.951801e+02  ...  8.008560e+02
           MSFT     3.052000e+01  3.110000e+01  ...  6.295000e+01
           YHOO              NaN           NaN  ...           NaN
Low        AMZN     1.257500e+02  1.264000e+02  ...  7.540000e+02
           GOOG     2.850957e+02  2.895219e+02  ...  7.902900e+02
           MSFT     3.001000e+01  3.026000e+01  ...  6.212000e+01
           YHOO              NaN           NaN  ...           NaN
Open       AMZN     1.279000e+02  1.291400e+02  ...  7.650000e+02
           GOOG     2.863824e+02  2.900634e+02  ...  8.004000e+02
           MSFT     3.026000e+01  3.031000e+01  ...  6.295000e+01
           YHOO              NaN           NaN  ...           NaN
Close      AMZN     1.291100e+02  1.273500e+02  ...  7.577700e+02
           GOOG     2.916481e+02  2.930192e+02  ...  7.908000e+02
           MSFT     3.035000e+01  3.096000e+01  ...  6.230000e+01
           YHOO              NaN           NaN  ...           NaN
Volume     AMZN     1.072320e+07  9.774900e+06  ...  4.828700e+06
           GOOG     1.307760e+07  8.535300e+06  ...  2.428300e+06
           MSFT     5.186350e+07  6.322810e+07  ...  4.220470e+07
           YHOO              NaN           NaN  ...           NaN
Adj Close  AMZN     1.291100e+02  1.273500e+02  ...  7.577700e+02
           GOOG     2.916481e+02  2.930192e+02  ...  7.908000e+02
           MSFT     2.413859e+01  2.462375e+01  ...  5.964758e+01
           YHOO              NaN           NaN  ...           NaN

Date                  2016-12-19    2016-12-20    2016-12-21    2016-12-22  \
Attributes Symbols
High       AMZN     7.705000e+02  7.743900e+02  7.712200e+02  7.712100e+02
           GOOG     7.976600e+02  7.986500e+02  7.966760e+02  7.933200e+02
           MSFT     6.377000e+01  6.380000e+01  6.370000e+01  6.410000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AMZN     7.561600e+02  7.677100e+02  7.657000e+02  7.630200e+02
           GOOG     7.862700e+02  7.932700e+02  7.871000e+02  7.885800e+02
           MSFT     6.242000e+01  6.303000e+01  6.312000e+01  6.341000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AMZN     7.588900e+02  7.686500e+02  7.700000e+02  7.681200e+02
           GOOG     7.902200e+02  7.967600e+02  7.958400e+02  7.923600e+02
           MSFT     6.256000e+01  6.369000e+01  6.343000e+01  6.384000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           MSFT     6.362000e+01  6.354000e+01  6.354000e+01  6.355000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AMZN     3.113200e+06  2.703600e+06  2.044600e+06  2.543600e+06
           GOOG     1.232100e+06  9.510000e+05  1.211300e+06  9.722000e+05
           MSFT     3.433820e+07  2.602840e+07  1.709630e+07  2.217660e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           MSFT     6.091138e+01  6.083479e+01  6.083479e+01  6.084436e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2016-12-23    2016-12-27    2016-12-28    2016-12-29  \
Attributes Symbols
High       AMZN     7.665000e+02  7.746500e+02  7.800000e+02  7.734000e+02
           GOOG     7.927400e+02  7.978600e+02  7.942300e+02  7.859300e+02
           MSFT     6.354000e+01  6.407000e+01  6.340000e+01  6.320000e+01
           YHOO              NaN           NaN           NaN           NaN
Low        AMZN     7.579900e+02  7.612000e+02  7.705000e+02  7.608500e+02
           GOOG     7.872800e+02  7.876570e+02  7.832000e+02  7.789200e+02
           MSFT     6.280000e+01  6.321000e+01  6.283000e+01  6.273000e+01
           YHOO              NaN           NaN           NaN           NaN
Open       AMZN     7.645500e+02  7.634000e+02  7.762500e+02  7.724000e+02
           GOOG     7.909000e+02  7.906800e+02  7.937000e+02  7.833300e+02
           MSFT     6.345000e+01  6.321000e+01  6.340000e+01  6.286000e+01
           YHOO              NaN           NaN           NaN           NaN
Close      AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           MSFT     6.324000e+01  6.328000e+01  6.299000e+01  6.290000e+01
           YHOO              NaN           NaN           NaN           NaN
Volume     AMZN     1.976900e+06  2.638700e+06  3.301000e+06  3.153500e+06
           GOOG     6.234000e+05  7.891000e+05  1.153800e+06  7.422000e+05
           MSFT     1.239800e+07  1.176320e+07  1.465330e+07  1.018160e+07
           YHOO              NaN           NaN           NaN           NaN
Adj Close  AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           MSFT     6.054756e+01  6.058586e+01  6.030820e+01  6.022204e+01
           YHOO              NaN           NaN           NaN           NaN

Date                  2016-12-30
Attributes Symbols
High       AMZN     7.674000e+02
           GOOG     7.827800e+02
           MSFT     6.299000e+01
           YHOO              NaN
Low        AMZN     7.482800e+02
           GOOG     7.704100e+02
           MSFT     6.203000e+01
           YHOO              NaN
Open       AMZN     7.664700e+02
           GOOG     7.827500e+02
           MSFT     6.296000e+01
           YHOO              NaN
Close      AMZN     7.498700e+02
           GOOG     7.718200e+02
           MSFT     6.214000e+01
           YHOO              NaN
Volume     AMZN     4.139400e+06
           GOOG     1.770000e+06
           MSFT     2.557990e+07
           YHOO              NaN
Adj Close  AMZN     7.498700e+02
           GOOG     7.718200e+02
           MSFT     5.949439e+01
           YHOO              NaN

[24 rows x 1763 columns]